name: Deploy Static Website to ec2

on:
  push:
    branches:
      - master  # or your working branch

jobs:
  deploy:
    runs-on: self-hosted  # Important for using your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.GCP_SSH_KEY }}" > racit.pem
        chmod 600 rachit.pem

    - name: Deploy to AWS VM via SCP
      run: |
        scp -i rachit.pem -o StrictHostKeyChecking=no -r ./public/* ubuntu@44.204.181.185:/var/www/html/

    - name: Restart Nginx
      run: |
        ssh -i rachit.pem -o StrictHostKeyChecking=no ubuntu@44.204.181.185 "sudo systemctl restart nginx"
