jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.GCP_SSH_KEY }}" > rachit.pem
        chmod 600 rachit.pem

    - name: Clean remote /var/www/html
      run: |
        ssh -i rachit.pem -o StrictHostKeyChecking=no ubuntu@44.204.181.185 "sudo rm -rf /var/www/html/*"

    - name: Deploy static site files
      run: |
        scp -i rachit.pem -o StrictHostKeyChecking=no -r ./* ubuntu@44.204.181.185:/var/www/html/

    - name: Restart nginx
      run: |
        ssh -i rachit.pem -o StrictHostKeyChecking=no ubuntu@44.204.181.185 "sudo systemctl restart nginx"
