name: Deploy Static Website to ec2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.GCP_SSH_KEY }}" > rachit.pem
        chmod 600 rachit.pem

    - name: Copy files to EC2 temp folder
      run: |
        ssh -i rachit.pem -o StrictHostKeyChecking=no ubuntu@44.204.181.185 "mkdir -p /home/ubuntu/tmp-site"
        scp -i rachit.pem -o StrictHostKeyChecking=no -r ./* ubuntu@44.204.181.185:/home/ubuntu/tmp-site/

    - name: Move files to /var/www/html
      run: |
        ssh -i rachit.pem -o StrictHostKeyChecking=no ubuntu@44.204.181.185 "sudo rm -rf /var/www/html/* && sudo mv /home/ubuntu/tmp-site/* /var/www/html/"

    - name: Restart nginx
      run: |
        ssh -i rachit.pem -o StrictHostKeyChecking=no ubuntu@44.204.181.185 "sudo systemctl restart nginx"
